[package]
authors = [
    "The CPAL contributors",
    "Pierre Krieger <pierre.krieger1708@gmail.com>",
]
description = "Low-level cross-platform audio playing library in pure Rust."
documentation = "https://docs.rs/cpal"
keywords = [
    "audio",
    "sound",
]
license = "Apache-2.0"
name = "cpal"
repository = "https://github.com/tomaka/cpal"
version = "0.8.2"

[dependencies]
lazy_static = "1.0"
parking_lot = "0.7"

[dev-dependencies]
hound = "3.0"
[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\"))".dependencies]
libc = "0.2"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\"))".dependencies.alsa-sys]
path = "alsa-sys"
version = "0.1"
[target."cfg(any(target_os = \"macos\", target_os = \"ios\"))".dependencies]
core-foundation-sys = "0.6.2"

[target."cfg(any(target_os = \"macos\", target_os = \"ios\"))".dependencies.coreaudio-rs]
default-features = false
features = [
    "audio_unit",
    "core_audio",
]
version = "0.9.0"
[target."cfg(target_os = \"emscripten\")".dependencies.stdweb]
default-features = false
version = "0.4.14"
[target."cfg(target_os = \"windows\")".dependencies.winapi]
features = [
    "audiosessiontypes",
    "audioclient",
    "coml2api",
    "combaseapi",
    "debug",
    "devpkey",
    "handleapi",
    "ksmedia",
    "mmdeviceapi",
    "objbase",
    "std",
    "synchapi",
    "winuser",
]
version = "0.3"
